Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::group(array("prefix" => "admin", "as"=>"admin."), function () {
        Route::group(['middleware' => 'auth:dcms'], function () {

                //faq
            Route::group(array("prefix" => "faq" ,"as"=>"faq."), function () {
                Route::get('{id}/copy', array('as'=>'copy', 'uses' => 'FaqController@copy'));
                
                //CATEGORIES
                Route::group(array("prefix" => "categories", "as"=>"categories."), function () {
                    Route::get('{id}/copy', array('as'=>'{id}.copy', 'uses' => 'CategoryController@copy'));
                    Route::any('api/table', array('as'=>'api.table', 'uses' => 'CategoryController@getDatatable'));
                });
                Route::resource('categories', '\Dcms\Faq\Http\Controllers\CategoryController');

                //API
                Route::group(array("prefix" => "api", "as"=>"api."), function () {
                    Route::any('table', array('as'=>'table', 'uses' => 'FaqController@getDatatable'));
                    Route::any('products/table/{faq_id?}', array('as'=>'products.table', 'uses' => 'FaqController@getProductsDatatable'));
                    Route::any("relation/table/{product_id?}", array("as"=>"relation.table", "uses" => "FaqController@getRelationDatatable"));
                    Route::any("plants/table/{faq_id?}", array("as"=>"plants.table", "uses" => "FaqController@getPlantsDatatable"));
                    Route::any("articles/table/{faq_id?}", array("as"=>"articles.table", "uses" => "FaqController@getArticlesDatatable"));
                    Route::any("faqrow", array("as"=>"faqrow", "uses" => "FaqController@getFaqrow"));
                });
            });
            Route::resource('faq', 'FaqController');
        });
    });
});

Models/Faq.php
<?php

namespace Dcms\Faq\Models;

use Dcms\Core\Models\EloquentDefaults;

class Faq extends EloquentDefaults
{
    protected $connection = 'project';
    protected $table = 'faq';

    public function detail()
    {
        return $this->hasMany('Dcms\Faq\Models\Detail', 'faq_id', 'id');
    }

    public function category()
    {
        return $this->belongsTo("Dcms\Faq\Models\Category", 'faq_category_id', 'id');
        //return $this->hasOne("Category");
    }

    public function productinformation()
    {
        return $this->belongsToMany('Dcms\Faq\Models\Information', 'faq_to_products_information_group', 'faq_id', 'information_id')->withTimestamps();
    }

    public function plants()
    {
        return $this->belongsToMany('Dcms\Plants\Models\Plant', 'faq_to_plant', 'faq_id', 'plant_id')->withTimestamps();
    }

    public function articles()
    {
        return $this->belongsToMany('Dcms\Dcmsarticles\Models\Article', 'article_to_faq', 'faq_id', 'article_id')->withTimestamps();
    }
}

Http/Controllers/FaqController.php
<?php

namespace Dcms\Faq\Http\Controllers;

use DB;
use Auth;
use Form;
use Mail;
use View;
use Input;
use Session;
use DateTime;
use Redirect;
use Validator;
use DataTables;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Dcms\Plants\Models\Plant;
use Dcms\Faq\Models\Faq;
use Dcms\Products\Models\Product;
use App\Http\Controllers\Controller;
use Dcms\Faq\Models\Detail;
use Dcms\Faq\Models\Category;
use Illuminate\Support\Facades\Schema;

class FaqController extends Controller
{
    public $faq_language_Columnnames = [];
    public $faq_Columnnames = [];
    public $faq_ColumnNamesDefaults = [];

    public $faqlanguageFormTemplate = "";
    public $faqFormTemplate = "";

    public $extendgeneralTemplate = "";

    public function __construct()
    {
        $this->middleware('permission:faq-browse')->only('index');
        $this->middleware('permission:faq-add')->only(['create', 'store']);
        $this->middleware('permission:faq-edit')->only(['edit', 'update']);
        $this->middleware('permission:faq-delete')->only('destroy');

        //note startdate and enddate are defaults, since these are always there, and have a specific value (not simple text, or bool)
        $this->faq_Columnnames = [
            'online'        => 'online',
        ];

        $this->faq_language_Columnnames = [
            'faq_category_id' => 'category_id',
            'question'               => 'question',
            'answer'         => 'answer',
            'sort_id' => 'sort_id',
            'slug' => 'slug',
        ];

        $this->faq_ColumnNamesDefaults = [
            ];

        $this->faqlanguageFormTemplate = null;
        $this->faqFormTemplate = null;
    }

    public static function getFaqDetailByLanguage($language_id = null)
    {
        return Detail::where("language_id", "=", $language_id)->lists("title", "id");
    }

    public static function getDropdownFaqByLanguage($language_id = null)
    {
        $dropdownvalues = FaqController::getFaqDetailByLanguage($language_id);

        return Form::select("faq[" . $language_id . "][]", $dropdownvalues, [3, 4, 5, 6], ["id" => "faq-" . $language_id, "multiple" => "multiple"]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $sectors = DB::connection('project')
            ->table('vwpages_language')
            ->select(
                'title',
                'language_id',
                'division'
            )
            ->where('depth', '=', '2')
            ->orderBy('title')
            ->get();

        // load the view
        return View::make('dcmsfaq::faq/index')->with('sectors', $sectors);
    }

    public function getDatatable()
    {
        $query = DB::connection('project')
            ->table('faq')
            ->select(
                'faq.id',
                'faq.online',
                'faq_language.question',
                'faq_language.id as faqlangid',
                (DB::connection("project")->raw('Concat("<img src=\'/packages/Dcms/Core/images/flag-",lcase(country),".svg\' style=\'width:16px; height:auto;\'>") as country'))
            )
            ->join('faq_language', 'faq.id', '=', 'faq_language.faq_id')
            ->leftJoin('languages', 'faq_language.language_id', '=', 'languages.id');
            
        if (intval(session('overrule_default_by_language_id')) > 0) {
            $query->where('faq_language.language_id', session('overrule_default_by_language_id'));
        }

        return Datatables::queryBuilder($query)
                        ->addColumn('edit', function ($model) {
                            return '<form method="POST" action="/admin/faq/'.$model->faqlangid.'" accept-charset="UTF-8" class="pull-right">
							<input name="_token" type="hidden" value="'.csrf_token().'">
							<input name="_method" type="hidden" value="DELETE">
							<a class="btn btn-xs btn-default" href="/admin/faq/'.$model->id.'/edit"><i class="far fa-pencil"></i></a>
							<button class="btn btn-xs btn-default" type="submit" value="Delete this faq" onclick="if(!confirm(\'Are you sure to delete this item?\')){return false;};"><i class="far fa-trash-alt"></i></button>
						</form>';
                        })
                        ->rawColumns(['country','edit'])
                        ->make(true) ;
    }

    /**
     * get the data for DataTable JS plugin.
     *
     * @return Response
     */
    public function getProductsDatatable($faq_id = 0)
    {
        $queryA = DB::connection('project')
        ->table('products_information as x')
        ->select(
            (
                DB::connection("project")->raw('
                case when (select count(*) from faq_to_products_information_group where faq_to_products_information_group.information_group_id = x.information_group_id and faq_id = "'.$faq_id.'") > 0 then 1 else 0 end as checked,
                catalogue,
                title,
                languages.country,
                information_group_id')
            )
        )
        ->leftJoin('languages', 'x.language_id', '=', 'languages.id')
        ->whereRaw('x.id IN (SELECT product_information_id FROM products_to_products_information WHERE product_id IN ( SELECT id FROM products WHERE online = 1 ) )')
        ->whereNotNull('x.information_group_id')
        ->orderBy('checked', 'DESC');

        $queryB = clone $queryA;
        $queryB->whereRaw('case when (select count(*) from faq_to_products_information_group where faq_to_products_information_group.information_group_id = x.information_group_id and faq_id = "'.$faq_id.'") > 0 then 1 else 0 end = 1');
        
        if (intval(session('overrule_default_by_language_id')) > 0) {
            $queryA->where('x.language_id', session('overrule_default_by_language_id'));
        }

        return Datatables::queryBuilder($queryB->union($queryA)->orderBy('checked', 'desc'))
                ->addColumn('radio', function ($model) {
                    return '<input type="checkbox" name="information_group_id[]" value="'.$model->information_group_id.'" '.($model->checked == 1?'checked="checked"':'').' id="chkbox_'.$model->information_group_id.'" > ';
                })
                ->addColumn('language', function ($model) {
                    return '<img src="/packages/Dcms/Core/images/flag-'.strtolower($model->country).'.svg" style="width:16px; height: auto;" alt="">';
                })
                ->rawColumns(['radio','language'])
                ->make(true);
    }

    public function getRelationDatatable($product_id = 0)
    {
        $information_group_id = 0;
        $ProductInformation = Product::with('information')->find($product_id);

        if (isset($ProductInformation->information) && !is_null($ProductInformation->information) && $ProductInformation->information()->count() > 0) {
            foreach ($ProductInformation->information as $I) {
                if (!is_null($I->information_group_id)) {
                    $information_group_id = $I->information_group_id;
                    break;
                }
            }
        }

        $queryA = DB::connection('project')
                                        ->table('faq_language as x')
                                        ->select(
                                            (
                                                DB::connection("project")->raw('
																	faq_id,
                                                                    title,
                                                                    languages.country,
																	case when (select count(*) from faq_to_products_information_group where faq_to_products_information_group.faq_id = x.faq_id and information_group_id = "'.$information_group_id.'") > 0 then 1 else 0 end as checked
																')
                                            )
                                        )
                                        ->leftJoin('languages', 'x.language_id', '=', 'languages.id')
                                        ->orderBy('checked', 'DESC');

        $queryB = clone $queryA;
        $queryB->whereRaw('case when (select count(*) from faq_to_products_information_group where faq_to_products_information_group.faq_id = x.faq_id and information_group_id = "'.$information_group_id.'") > 0 then 1 else 0 end = 1');
                                           
        if (intval(session('overrule_default_by_language_id')) > 0) {
            $queryA->where('x.language_id', session('overrule_default_by_language_id'));
        }

        return Datatables::queryBuilder($queryB->union($queryA)->orderBy('checked', 'desc'))
                        ->addColumn('radio', function ($model) {
                            return '<input type="checkbox" name="faq_id[]" value="'.$model->faq_id.'" '.($model->checked == 1?'checked="checked"':'').' id="chkbox_'.$model->faq_id.'" > ';
                        })
                        ->addColumn('language', function ($model) {
                            return '<img src="/packages/Dcms/Core/images/flag-'.strtolower($model->country).'.svg" style="width:16px; height: auto;" alt="">';
                        })
                        ->rawColumns(['radio','language'])
                        ->make(true) ;
    }

    public function getPlantsDatatable($faq_id = null)
    {
        $queryA = DB::connection('project')
        ->table('plants_language as x')
        ->select(
            (
                DB::connection("project")->raw('
                case when (select count(*) from faq_to_plant where faq_to_plant.plant_id = x.plant_id and faq_id = "'.$faq_id.'") > 0 then 1 else 0 end as checked,
                languages.country,
                x.plant_id, 
                x.common')
            )
        )
        ->leftJoin('languages', 'x.language_id', '=', 'languages.id')
        ->orderBy('checked', 'DESC');
        

resources/views/faq/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Faq</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li class="active"><i class="far fa-newspaper"></i> Faq</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    @can('faq-add')
                        <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('/admin/faq/create') !!}">Create new</a></div>
                    @endcan

                    <h2>Overview</h2>
                    
                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Online</th>
                            <th>Question</th>
                            <th>Country</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {

                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.faq.api.table') }}",
                                "columns": [
                                    {data: 'id', name: 'ID'},
                                    {data: 'online', name: 'faq.online'},
                                    {data: 'question', name: 'faq_language.question'},
                                    {data: 'country', name: 'country', searchable: false},
                                    {data: 'edit', name: 'edit', orderable: false, searchable: false}
                                ]
                            });
                        });
                    </script>

                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

                </div>
            </div>
        </div>
    </div>
@stop

@section("script")
    <script type="text/javascript">

        languageFilter = "";
        divisionFilter = "";

        $(document).ready(function () {
            $('.sectordd').hide();
            filterLanguage();
            filterDivision();

            $('.changeLanguage').change(function () {
                filterLanguage();
            })

            $('.changeDivision').change(function () {
                filterDivision();
            })

            //Filter toggle
            $('.filter .panel-heading').click(function () {
                $(this).closest('.panel').toggleClass('up');
            });

            $("#btn-reset").click(function () {
                var appendDiv = jQuery($(".condition:last")[0].outerHTML);
                $(".condition").remove();
                $("#filters").prepend(appendDiv.attr('id', '0'));
                $("#0").find('select').val('0');
                $("#0").find('input[type=text]').val('');
            });

            //Add condition
            $('.add-condition').click(function () {
                var id = $(".condition:last").attr('id');
                var appendDiv = jQuery($(".condition:last")[0].outerHTML);

                appendDiv.attr('id', ++id).insertAfter(".condition:last");

                $("#" + id).find('select').val('0');
                $("#" + id).find('input[type=text]').val('');

                return false;
            });

        });
    </script>
@stop